using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SubscriptionPlusDesktop.Services.NLP
{
    public class NLPData
    {
        protected readonly HashSet<string> _stopWords;
        protected readonly Dictionary<string, string> _lemmasDictionary;

        public NLPData()
        {
            var words = new[]
            {
                "i","me","my","myself","we","our","ours","us","this","these","those",
                "he","she","it","its","itself","them","their","by","from","into","during",
                "after","before","above","below","but","or","as","if","then","else","so",
                "will","would","shall","should","can","could","may","might","must",
                "here","there","now","just","very","too","about","again","once","been",
                "being","both","each","few","more","most","other","some","such","what",
                "which","why","how","the", "a", "an", "and", "any", "are", "around", "at", "away", "be", "because", "been",
                "below", "between", "both", "can", "come", "could", "did", "do", "down", "each", "even",
                "every", "for", "from", "get", "had", "has", "have", "her", "him", "his", "how", "if",
                "in", "into", "is", "it", "its", "just", "like", "made", "make", "many", "may", "more",
                "much", "must", "no", "not", "off", "on", "only", "or", "other", "our", "out", "over",
                "re", "said", "same", "see", "she", "should", "so", "some", "such", "take", "than", "that",
                "the", "their", "theirs", "them", "themselves", "then", "there", "there's",
                "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through",
                "to", "too", "under", "up", "upon", "us", "very", "was", "we", "well", "were", "what",
                "when", "where", "why", "will", "with", "would", "you", "your", "when", "where", "why", "how",
                "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", 
                "aren't", "as", "at", "be", "because", "been", "before", "being", "below", "between", 
                "both", "but", "by", "can't", "cannot", "could", "couldn't", "did", "didn't",
                "do", "does", "doesn't", "doing", "don't", "down", "during", "each", "few", "for", "from", 
                "further", "had", "hadn't", "has", "hasn't", "have", "haven't", "having", "he", 
                "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself",
                "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", 
                "is", "isn't", "it", "it's", "its", "itself", "let's", "me", "more", "most", "mustn't", 
                "my", "myself", "no", "nor", "not", "of", "off", "on", "once", "only", "or", "other", "ought",
                "our", "ours", "ourselves", "out", "over", "own", "same", "shan't", "she", "she'd", 
                "she'll", "she's", "should", "shouldn't", "so", "some", "such", "than", "that", "that's", 
                "the", "their", "theirs", "them", "themselves", "then", "there", "there's",
                "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", 
                "to", "too", "under", "until", "up", "very", "was", "wasn't", "we", "we'd", "we'll", 
                "we're", "we've", "were", "weren't", "what", "what's", "when", "when's", "where",
                "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "won't", 
                "would", "wouldn't", "you", "you'd", "you'll", "you're", "you've", "your", "yours", 
                "yourself", "yourselves", "de", "il", "la",  "le", "les", "un", "une", "des", "et", "du", "à", "en",
                "и", "в", "во", "не", "что", "он", "на", "я", "с", "со", "как", "а", "то", "все", "она",
                "так", "его", "мне", "но", "по", "из", "еще", "нет", "для", "мы", "вы", "им", "бы", "ли",
                "за", "от", "к", "до", "у", "же", "об", "о", "или", "без", "конечно", "да", "после", "перед",
                "над", "под", "около", "вокруг", "через", "однако", "ведь", "очень", "сразу", "совсем",
                "всегда", "никогда", "даже", "только", "уже", "ему", "тот", "один", "другой", "этот", "который",
                "свой", "сам", "ее", "их", "ей", "им", "тем", "тех", "той", "том", "тот", "при", "про", "без",
                "даже", "зачем", "почему", "когда", "где", "куда", "откуда", "чтобы", "чтоб", "хоть", "хотя",
                "будет", "быть", "был", "была", "были", "было", "есть", "быть", "может", "можно", "нужно",
                "надо", "очень", "совсем", "давно", "недавно", "рано", "поздно", "тут", "там", "сюда", "туда",
                "отсюда", "оттуда", "поэтому", "значит", "например", "потом", "далее", "кроме", "среди",
                 "более", "больше", "будто", "вам", "вас", "весь", "всей", "вместе", "вообще", "восемь", "вот", "впрочем", "всю",
                "где", "два", "движение", "две", "девять", "делать", "делаю", "для", "едва", "если", "зачем", "здесь",
                "из-за", "из-под", "имеет", "имел", "именно", "иной", "иногда", "к", "каждая", "каждое", "каждые", "каждый",
                "какая", "какое", "какие", "какой", "каком", "кому", "конечно", "когда", "которая", "которого", "которой",
                "которые", "который", "кроме", "кто", "куда", "либо", "лишь", "лучше", "между", "меня", "много", "может",
                "мой", "моя", "мое", "мои", "наверное", "над", "надо", "наконец", "нам", "нас", "нее", "ней", "нем",
                "несколько", "него", "них", "ничего", "ну", "пять", "один", "одна", "однажды", "они", "оно", "опять",
                "перед", "по", "под", "потом", "потому", "почему", "почти", "при", "про", "раз", "разве", "раньше", "рядом",
                "сам", "сама", "сами", "само", "самой", "свой", "свое", "свои", "сейчас", "семь", "сих", "сказал", "сказала",
                "сказали", "сказало", "сказать", "сколько", "со", "такая", "такое", "такие", "такой", "там", "тебя", "тем",
                "теперь", "течь", "тобой", "только", "том", "тот", "три", "тут", "ты", "уже", "хоть", "хотя", "чего",
                "человек", "чем", "четыре", "чуть", "шесть", "это", "эта", "эти", "этот",
            };

            this._stopWords = new HashSet<string>(words);

            var rawLemmas = new List<KeyValuePair<string, string>>()
            {
                new KeyValuePair<string, string>("am", "be"), new KeyValuePair<string, string>("is", "be"), new KeyValuePair<string, string>("are", "be"), new KeyValuePair<string, string>("was", "be"), new KeyValuePair<string, string>("were", "be"),
                new KeyValuePair<string, string>("has", "have"), new KeyValuePair<string, string>("had", "have"),
                new KeyValuePair<string, string>("does", "do"), new KeyValuePair<string, string>("did", "do"),
                new KeyValuePair<string, string>("going", "go"), new KeyValuePair<string, string>("goes", "go"), new KeyValuePair<string, string>("went", "go"),
                new KeyValuePair<string, string>("made", "make"), new KeyValuePair<string, string>("making", "make"),
                new KeyValuePair<string, string>("saw", "see"), new KeyValuePair<string, string>("seen", "see"), new KeyValuePair<string, string>("seeing", "see"),
                new KeyValuePair<string, string>("came", "come"), new KeyValuePair<string, string>("coming", "come"),
                new KeyValuePair<string, string>("took", "take"), new KeyValuePair<string, string>("takes", "take"), new KeyValuePair<string, string>("taken", "take"), new KeyValuePair<string, string>("taking", "take"),
                new KeyValuePair<string, string>("better", "good"), new KeyValuePair<string, string>("best", "good"),
                new KeyValuePair<string, string>("worse", "bad"), new KeyValuePair<string, string>("worst", "bad"),
                new KeyValuePair<string, string>("bigger", "big"), new KeyValuePair<string, string>("biggest", "big"),
                new KeyValuePair<string, string>("smaller", "small"), new KeyValuePair<string, string>("smallest", "small"),
                new KeyValuePair<string, string>("larger", "large"), new KeyValuePair<string, string>("largest", "large"),
                new KeyValuePair<string, string>("more", "many"), new KeyValuePair<string, string>("most", "many"),
                new KeyValuePair<string, string>("less", "little"), new KeyValuePair<string, string>("least", "little"),
                new KeyValuePair<string, string>("further", "far"), new KeyValuePair<string, string>("furthest", "far"),
                new KeyValuePair<string, string>("children", "child"),
                new KeyValuePair<string, string>("people", "person"),
                new KeyValuePair<string, string>("lives", "life"), new KeyValuePair<string, string>("life", "life"),
                new KeyValuePair<string, string>("wives", "wife"),
                new KeyValuePair<string, string>("fewer", "few"), new KeyValuePair<string, string>("fewest", "few"),
                new KeyValuePair<string, string>("ran", "run"),
                new KeyValuePair<string, string>("spoke", "speak"), new KeyValuePair<string, string>("spoken", "speak"),
                new KeyValuePair<string, string>("wrote", "write"), new KeyValuePair<string, string>("written", "write"),
                new KeyValuePair<string, string>("ate", "eat"), new KeyValuePair<string, string>("eaten", "eat"),
                new KeyValuePair<string, string>("drank", "drink"), new KeyValuePair<string, string>("drunk", "drink"),
                new KeyValuePair<string, string>("slept", "sleep"),
                new KeyValuePair<string, string>("fought", "fight"),
                new KeyValuePair<string, string>("found", "find"),
                new KeyValuePair<string, string>("kept", "keep"),
                new KeyValuePair<string, string>("left", "leave"),
                new KeyValuePair<string, string>("met", "meet"),
                new KeyValuePair<string, string>("paid", "pay"),
                new KeyValuePair<string, string>("read", "read"),
                new KeyValuePair<string, string>("sat", "sit"),
                new KeyValuePair<string, string>("sold", "sell"),
                new KeyValuePair<string, string>("thought", "think"),
                new KeyValuePair<string, string>("understood", "understand"),
                new KeyValuePair<string, string>("won", "win"),
                new KeyValuePair<string, string>("houses", "house"),
                new KeyValuePair<string, string>("men", "man"),
                new KeyValuePair<string, string>("women", "woman"),
                new KeyValuePair<string, string>("feet", "foot"),
                new KeyValuePair<string, string>("teeth", "tooth"),
                new KeyValuePair<string, string>("mice", "mouse"),
                new KeyValuePair<string, string>("oxen", "ox"),
                new KeyValuePair<string, string>("indices", "index"),

                new KeyValuePair<string, string>("люди", "человек"),
                new KeyValuePair<string, string>("дети", "ребенок"),
                new KeyValuePair<string, string>("идут", "идти"), new KeyValuePair<string, string>("ходил", "идти"), new KeyValuePair<string, string>("ходили", "идти"),
                new KeyValuePair<string, string>("хороший", "хороший"), new KeyValuePair<string, string>("лучший", "хороший"),
                new KeyValuePair<string, string>("плохой", "плохой"), new KeyValuePair<string, string>("худший", "плохой"),
                new KeyValuePair<string, string>("была", "быть"), new KeyValuePair<string, string>("были", "быть"), new KeyValuePair<string, string>("было", "быть"),
                new KeyValuePair<string, string>("знал", "знать"), new KeyValuePair<string, string>("знает", "знать"),
                new KeyValuePair<string, string>("дома", "дом"),
                new KeyValuePair<string, string>("года", "год"), new KeyValuePair<string, string>("году", "год"), new KeyValuePair<string, string>("лет", "год"),
                new KeyValuePair<string, string>("времени", "время"), new KeyValuePair<string, string>("время", "время"),
                new KeyValuePair<string, string>("руками", "рука"),

                new KeyValuePair<string, string>("bought", "buy"), new KeyValuePair<string, string>("brought", "bring"),
                new KeyValuePair<string, string>("caught", "catch"), new KeyValuePair<string, string>("taught", "teach"),
                new KeyValuePair<string, string>("felt", "feel"), new KeyValuePair<string, string>("found", "find"),
                new KeyValuePair<string, string>("got", "get"), new KeyValuePair<string, string>("given", "give"), new KeyValuePair<string, string>("gave", "give"),
                new KeyValuePair<string, string>("heard", "hear"), new KeyValuePair<string, string>("held", "hold"),
                new KeyValuePair<string, string>("knew", "know"), new KeyValuePair<string, string>("known", "know"),
                new KeyValuePair<string, string>("led", "lead"), new KeyValuePair<string, string>("lost", "lose"),
                new KeyValuePair<string, string>("meant", "mean"),
                new KeyValuePair<string, string>("put", "put"), new KeyValuePair<string, string>("read", "read"),
                new KeyValuePair<string, string>("said", "say"), new KeyValuePair<string, string>("sent", "send"), new KeyValuePair<string, string>("shown", "show"), new KeyValuePair<string, string>("showed", "show"),
                new KeyValuePair<string, string>("sung", "sing"), new KeyValuePair<string, string>("sang", "sing"),
                new KeyValuePair<string, string>("taken", "take"), new KeyValuePair<string, string>("told", "tell"),
                new KeyValuePair<string, string>("understood", "understand"),
                new KeyValuePair<string, string>("worn", "wear"), new KeyValuePair<string, string>("wore", "wear"),
                new KeyValuePair<string, string>("won", "win"),
                new KeyValuePair<string, string>("came", "come"), new KeyValuePair<string, string>("coming", "come"),
                new KeyValuePair<string, string>("feet", "foot"), new KeyValuePair<string, string>("geese", "goose"),
                new KeyValuePair<string, string>("formulae", "formula"), new KeyValuePair<string, string>("data", "datum"),
                
                new KeyValuePair<string, string>("говорил", "говорить"), new KeyValuePair<string, string>("говорят", "говорить"),
                new KeyValuePair<string, string>("думал", "думать"), new KeyValuePair<string, string>("думают", "думать"),
                new KeyValuePair<string, string>("делал", "делать"), new KeyValuePair<string, string>("делают", "делать"),
                new KeyValuePair<string, string>("сказал", "сказать"), new KeyValuePair<string, string>("сказали", "сказать"),
                new KeyValuePair<string, string>("вижу", "видеть"), new KeyValuePair<string, string>("видел", "видеть"), new KeyValuePair<string, string>("видели", "видеть"),
                new KeyValuePair<string, string>("могу", "мочь"), new KeyValuePair<string, string>("может", "мочь"), new KeyValuePair<string, string>("могли", "мочь"),
                new KeyValuePair<string, string>("хочу", "хотеть"), new KeyValuePair<string, string>("хочет", "хотеть"), new KeyValuePair<string, string>("хотели", "хотеть"),
                new KeyValuePair<string, string>("знаю", "знать"), new KeyValuePair<string, string>("знаешь", "знать"),
                new KeyValuePair<string, string>("деньги", "деньги"), new KeyValuePair<string, string>("средства", "средство"),
                new KeyValuePair<string, string>("месяца", "месяц"), new KeyValuePair<string, string>("месяцев", "месяц"),
                new KeyValuePair<string, string>("года", "год"), new KeyValuePair<string, string>("году", "год"), new KeyValuePair<string, string>("лет", "год"),
                new KeyValuePair<string, string>("людей", "человек"), new KeyValuePair<string, string>("человека", "человек"),
                new KeyValuePair<string, string>("женщин", "женщина"), new KeyValuePair<string, string>("мужчин", "мужчина"),
                new KeyValuePair<string, string>("вещи", "вещь"),
                new KeyValuePair<string, string>("города", "город"), new KeyValuePair<string, string>("городам", "город"),
                new KeyValuePair<string, string>("страны", "страна"), new KeyValuePair<string, string>("странам", "страна"),
                new KeyValuePair<string, string>("дома", "дом"), new KeyValuePair<string, string>("домов", "дом"),
                new KeyValuePair<string, string>("книги", "книга"), new KeyValuePair<string, string>("книгам", "книга"),
                new KeyValuePair<string, string>("слова", "слово"), new KeyValuePair<string, string>("слов", "слово"),
                new KeyValuePair<string, string>("информации", "информация"),
                new KeyValuePair<string, string>("продуктов", "продукт"), new KeyValuePair<string, string>("продукты", "продукт"),
                new KeyValuePair<string, string>("услуги", "услуга"), new KeyValuePair<string, string>("услуг", "услуга"),
                new KeyValuePair<string, string>("системы", "система"), new KeyValuePair<string, string>("систем", "система"),
                new KeyValuePair<string, string>("приложения", "приложение"), new KeyValuePair<string, string>("приложений", "приложение"),
                new KeyValuePair<string, string>("пользователей", "пользователь"), new KeyValuePair<string, string>("пользователю", "пользователь"),
                new KeyValuePair<string, string>("даты", "дата"), new KeyValuePair<string, string>("дат", "дата"),
                new KeyValuePair<string, string>("цены", "цена"), new KeyValuePair<string, string>("ценой", "цена"),
                new KeyValuePair<string, string>("оплаты", "оплата"), new KeyValuePair<string, string>("платежей", "платеж"), new KeyValuePair<string, string>("платежа", "платеж")
            };

            this._lemmasDictionary = rawLemmas.GroupBy(kvp => kvp.Key, StringComparer.OrdinalIgnoreCase).ToDictionary(g => g.Key, g => g.Last().Value, StringComparer.OrdinalIgnoreCase);
        }
    }
}
